# the blogs name
brand = "lastlog.de/blog"

# input and output directory (both served by the webserver)
input = "documents/lastlog.de"
output = "documents/output"

# assets are js/css/... files and they can be added to the input directory or used from pankat
assets = "documents/assets"

# pankat specific wasm runtime for interactive changes in the webpage
wasm = "documents/wasm"

# folder where the pankat.sqlite database is located
database = "documents"

# weather to build only the documents or update them in real time using websocket connection
static_build_only = false

# the port for the pankat webserver, point your browser to localhost:5000
port = 5000

# instead of passing the token from here, use PANKAT_JWT_TOKEN environment variable
jwt_token = "not set"

# admin user password
admin_password = "not set"

# documents/mydir/myarticle.mdwn -> documents/output/myarticle.html with flat being true
flat = true
